[package]
name = "ruffman"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ruf"
path = "src/main.rs"

[dependencies]
bitvec = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3.0"
serde_bytes = "0.11"
